### ISSUE TITLE
New logo design

### ISSUE THREAD

**Issue by abhishalya** [julia-actions/example-workflows#4]
Part of Google [Code-in task](https://codein.withgoogle.com/dashboard/task-instances/5878130405801984/).

![image](https://user-images.githubusercontent.com/34682737/71261357-2bb15d80-2363-11ea-9c40-0efc2c1352d8.png)

[LICENSE.txt](https://github.com/julia-actions/example-workflows/files/3988654/LICENSE.txt)

**Comment by logankilpatrick** [comment]
Hey @SaschaMann and @davidanthoff This task was created to make a logo for the Julia Actions Org. Great job @abhishalya

**Comment by davidanthoff** [comment]
Looks great!

**Comment by abhishalya** [comment]
@davidanthoff Would you mind having it as org logo?

**Comment by davidanthoff** [comment]
Not at all, I think it would be great. @SaschaMann started the org, so he should probably make the final call.

**Comment by SaschaMann** [comment]
This looks great, thank you!

Could you add some padding to make it square? GitHub won't let me upload it without cropping. :/

And perhaps make the arrows/lines slightly thicker if that's possible, they're a bit hard to see in the profile view:

![grafik](https://user-images.githubusercontent.com/20866761/71305864-f4ca5e80-23d9-11ea-9f7f-67eef6f38521.png)

**Comment by abhishalya** [comment]
Have a look at this:

![image](https://user-images.githubusercontent.com/34682737/71308695-b6f32780-2425-11ea-91c9-075081ad53f8.png)

@SaschaMann

**Comment by SaschaMann** [comment]
@abhishalya Nice! That works better :)

I think it might be useful to move it into a repo, especially if you happen to have an svg file. I can create a logo repo in the org if you want. What do you think?

**Comment by abhishalya** [comment]
@SaschaMann Sure, I do have the svg file.

**Comment by SaschaMann** [comment]
Created a repo and sent you an [invite](https://github.com/julia-actions/logo/invitations). You can upload it and the licence directly to master there or open a PR.

**Comment by abhishalya** [comment]
I'm not able to push to master for some reason, I've accepted the invite

**Comment by abhishalya** [comment]
Oh, seems like its related to 2FA

**Comment by SaschaMann** [comment]
2FA is enforced for the entire org, even for single-repo-collaborators. You could fork it and submit a PR if you don't want to set it up (though I'd highly recommend enabling 2FA!)

**Comment by abhishalya** [comment]
Yep, enabled it. Also added the logo
